name: ae_form
description: "A new Flutter package project."
version: 0.1.0
homepage: "https://github.com/AErmek/ae_form"
publish_to: none

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.27.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
